"""add_foreign_key_indexes

Revision ID: 3239321950ae
Revises: f80b6406a8de
Create Date: 2026-07-22 11:31:29.662121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3239321950ae'
down_revision: Union[str, Sequence[str], None] = 'f80b6406a8de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attendances_athlete_id'), 'attendances', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_attendances_session_id'), 'attendances', ['session_id'], unique=False)
    op.create_index(op.f('ix_equipment_facility_id'), 'equipment', ['facility_id'], unique=False)
    op.create_index(op.f('ix_injury_records_athlete_id'), 'injury_records', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_memberships_athlete_id'), 'memberships', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_performance_records_athlete_id'), 'performance_records', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_performance_records_competition_id'), 'performance_records', ['competition_id'], unique=False)
    op.create_index(op.f('ix_performance_records_session_id'), 'performance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_coach_id'), 'training_sessions', ['coach_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_facility_id'), 'training_sessions', ['facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_sessions_facility_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_coach_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_performance_records_session_id'), table_name='performance_records')
    op.drop_index(op.f('ix_performance_records_competition_id'), table_name='performance_records')
    op.drop_index(op.f('ix_performance_records_athlete_id'), table_name='performance_records')
    op.drop_index(op.f('ix_memberships_athlete_id'), table_name='memberships')
    op.drop_index(op.f('ix_injury_records_athlete_id'), table_name='injury_records')
    op.drop_index(op.f('ix_equipment_facility_id'), table_name='equipment')
    op.drop_index(op.f('ix_attendances_session_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_athlete_id'), table_name='attendances')
    # ### end Alembic commands ###
